### ISSUE TITLE
hastane otomasyonu

### ISSUE THREAD

**Issue by sudenazeyigun** [sercel23/Hospital-Automation#1]
Öncelikle merhaba. Hastane otomasyonunu örneğinizi çok beğendim. Rica etsem veri tabanınızı gösterebilir misiniz? Ekran görüntüsü ile olabilir kodlara baktığımda biraz kafam karıştı da. Şimdiden teşekkür ederim.

**Comment by SerapErcel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hasta Profil Sayfası Güncelleme](https://trello.com/c/kB318lAZ/89-hasta-profil-sayfas%C4%B1-g%C3%BCncelleme)
